### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by xuanmd** [Maithanhdanh/express-typescript-boilerplate#10]
How can we deploy this template to the hosting provider? For example: Heroku.
I've tried to deploy with Procfile:  `npm start` or `node build/index.js`
But it didn't work and show warnings of missing modules or cannot found files.
Please help to give a guidance for that. Really appreciate your help!

**Comment by Maithanhdanh** [comment]
Can you provide me with more info about this issue? Or image of the issue much better

**Comment by xuanmd** [comment]
**Heroku deployment issue:**
After running the build process successfully, Heroku runs the command to serve the app (`node build/index.js`). But it throws the error about the module resolve (cannot find module: `build/config/logger`).
<img width="674" alt="Screen Shot 2022-05-27 at 17 57 21" src="https://user-images.githubusercontent.com/38640879/170686777-6e93cc5b-4398-4464-bdd3-f75d4247aa51.png">

And I come up with this thread and solution for that
https://github.com/ilearnio/module-alias/issues/74#issuecomment-777405382

Btw, it also requires the `tslib` installed as dependencies, not devDependencies.
<img width="676" alt="Screen Shot 2022-05-27 at 17 58 21" src="https://user-images.githubusercontent.com/38640879/170686883-cf75325e-d72e-4c5e-998b-9b62698558da.png">

**Comment by Maithanhdanh** [comment]
So, go ahead, create a pull request for me please ^.^

**Comment by Maithanhdanh** [comment]
I see `tslib` is already in dependencies, so I gonna close the issue.
